### ISSUE TITLE
antivirus popped up that you have a crypto miner in your JS

### ISSUE THREAD

**Issue by tetreault** [jensimmons/jensimmons.com#1]
Hello, 

Randomly came across your github. I clicked on your site link and my Avast antivirus popped up a gnarly warning that you have a crypto miner in your JS. 

<img width="327" alt="Screen Shot 2019-04-17 at 8 55 19 AM" src="https://user-images.githubusercontent.com/5934354/56289407-d693bc80-60ee-11e9-9fbd-7472a482d80a.png">

**Comment by jensimmons** [comment]
Thanks. That was on the old site, running Drupal. I've since burned down that site, and replaced it with what I was building on this Git repo — a static site, generated by 11ty. Thanks for making sure I knew.
